
exp-id: test
seed: 1
dataset: Nuscenes
model_type: Autobot-Ego # Autobot-Joint # using the raw road segments in the map
num_modes: 10
hidden_size: 128
num_encoder_layers: 2
num_decoder_layers: 2
dropout: 0.1
entropy_weight: 40.0
kl_weight: 20.0
use_FDEADE_aux_loss: True
use_map_lanes: True # using the raw road segments in the map
use_map_image: False # using the Birds-eye-view image of the road network
tx_hidden_size: 384
batch_size: 64
learning_rate: 0.00075
learning_rate_sched: [10, 20, 30, 40, 50]
dataset_path: /home/luca/Documents/nuscenes/h5_files
